### ISSUE TITLE
kubernetes: change ps to job?

### ISSUE THREAD

**Issue by sahildua2305** [zhoudongyan/wide-and-deep#1]
I noticed that in your kubernetes yaml configuration, you have used `job` for worker and master servers, however, you have used `ReplicationController` for the ps server. Is that intentional? If so, why?

**Comment by zhoudongyan** [comment]
Either `ReplicationController` or `Job` for the ps server is ok. The ps server will not terminate automatically because it call a blocking method `join()`.

**Comment by sahildua2305** [comment]
Ah okay, makes sense.
